### ISSUE TITLE
SHA-256 password hashing is not secure

### ISSUE THREAD

**Issue by akx** [saderror256/starchat#8]
It appears this project uses plain SHA-256 hashes for passwords, which is not secure:

https://github.com/saderror256/starchat/blob/a3fa7967b85989dbbd956df6fefa3c2c4fc2ea95/create.php#L52

Please refer to [this excellent article](https://codahale.com/how-to-safely-store-a-password/) on how to safely store passwords.

**Comment by saderror256** [comment]
I was told i should try salting as well? I think the function is called password_hash?

**Comment by saderror256** [comment]
I have hit a huge roadblock actually, we cannot use bcrypt yet because it is introduced in a later version of php. Once old php version get discontinued which i heard is very soon we will change this, thanks, we are sticking with sha256 for now

**Comment by saderror256** [comment]
i actually feel idiotic now as appearently centos 7 php is deprecated now, so nevermind, i will keep the function, so your request has been done, i need to update my software, i hate centos but my provider forces me to use it
