### ISSUE TITLE
Suggestion - Bootstrap 4 for frontend

### ISSUE THREAD

**Issue by turtle0x1** [saderror256/starchat#9]
As the title says bootstrap is a great frontend framework

**Comment by saderror256** [comment]
I will think about it but sticking to no frameworks makes it very lightweight :), but at the sametime it would look better with bootstrap

**Comment by saderror256** [comment]
The only downside is there isnt too much stuff we can use, as bootstrap is more made for basic websites, and we are dealing with a chat application, so i think for now we may include it in the login but for home.php it won't look to great

**Comment by saderror256** [comment]
![screenshot from 2018-10-17 13-01-59](https://user-images.githubusercontent.com/43082574/47103316-024feb80-d20d-11e8-9ba3-9cef96a645bd.png)
This does look better, let me play with this some and we will see

**Comment by saderror256** [comment]
Completed
